#!/bin/bash -l
#SBATCH -o ./logs/%A.out
#SBATCH -e ./logs/%A.err
#SBATCH --job-name=Claude
#SBATCH --mail-type=ALL
#SBATCH --mail-user=akshaykjagadish@gmail.com
#SBATCH --time=72:00:00
#SBATCH --cpus-per-task=18


cd ~/ermi/categorisation/task_generation

module purge
module load anaconda/3/2021.11
# pip3 install --user accelerate openai gym ipdb transformers tensorboard python-dotenv
# pip3 install --user fire sentencepiece ipdb accelerate tqdm
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}


# python generate_tasks.py --model NA --task functionlearning --proc-id 0  --num-tasks 10 --start-task-id 0 --num-dim 1 --num-data 20 --max-length 100000 --run-gpt claude --prompt-version 2 --use-generated-tasklabels --file-name-tasklabels claude_synthesized_functionlearning_problems_paramsNA_dim1_tasks10_run0_procid0_pversion0  --path-tasklabels /u/ajagadish/ermi/categorisation/data/tasklabels
python generate_data.py --model NA --task functionlearning --proc-id 0  --num-tasks 9991 --start-task-id 0 --num-dim 1 --num-data 20 --max-length 100000 --run-gpt claude --prompt-version 2 --file-name-tasklabels claude_synthesized_functionlearning_problems_paramsNA_dim1_tasks9991_pversion0  --path-tasklabels /u/ajagadish/ermi/functionlearning/data/synthesize_problems

# prompt version 5, num-dim 4 iterative first and second stage

## first stage
# python generate_tasks.py --model NA  --stage 1 --proc-id 0  --num-tasks 1000 --start-task-id 0 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 1  --num-tasks 1000 --start-task-id 383 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 2  --num-tasks 1000 --start-task-id 466 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 3  --num-tasks 1000 --start-task-id 1466 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 4  --num-tasks 1000 --start-task-id 2308 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 5  --num-tasks 1000 --start-task-id 2692 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 6  --num-tasks 1000 --start-task-id 3376 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 7  --num-tasks 1000 --start-task-id 3406 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 8  --num-tasks 1000 --start-task-id 3500 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 9  --num-tasks 1000 --start-task-id 3568 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 10  --num-tasks 1000 --start-task-id 4429 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 11  --num-tasks 1000 --start-task-id 5429 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 12  --num-tasks 1000 --start-task-id 6429 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 13  --num-tasks 1000 --start-task-id 7429 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 13  --num-tasks 1000 --start-task-id 7543 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA  --stage 1 --proc-id 14 --num-tasks 1000 --start-task-id 7950 --num-dim 4 --num-data 650 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim4_tasks20690_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels

# prompt version 5, num-dim 6 iterative first and second stage
## first stage
# (DONE)   python generate_tasks.py --model NA --stage 1 --proc-id 0  --num-tasks 1000 --start-task-id 0     --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED) python generate_tasks.py --model NA --stage 1 --proc-id 1  --num-tasks 1000 --start-task-id 1001  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED) python generate_tasks.py --model NA --stage 1 --proc-id 2  --num-tasks 1000 --start-task-id 1079  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (DONE)   python generate_tasks.py --model NA --stage 1 --proc-id 4  --num-tasks 604  --start-task-id 1473  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED) python generate_tasks.py --model NA --stage 1 --proc-id 3  --num-tasks 3000 --start-task-id 2078  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (DONE)   python generate_tasks.py --model NA --stage 1 --proc-id 5  --num-tasks 3000 --start-task-id 2659  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED) python generate_tasks.py --model NA --stage 1 --proc-id 6  --num-tasks 3000 --start-task-id 5659  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED) python generate_tasks.py --model NA --stage 1 --proc-id 7  --num-tasks 3000 --start-task-id 7747  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED) python generate_tasks.py --model NA --stage 1 --proc-id 8  --num-tasks 3000 --start-task-id 10747 --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED at 12910) python generate_tasks.py --model NA --stage 1 --proc-id 9  --num-tasks 3000 --start-task-id 12714 --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (FAILED at 10693) python generate_tasks.py --model NA --stage 1 --proc-id 10  --num-tasks 950 --start-task-id 9797 --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels

## second stage
# (done) python generate_tasks.py --model NA --stage 2 --proc-id 0  --num-tasks 1000 --start-task-id 0 --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done) python generate_tasks.py --model NA --stage 2 --proc-id 1  --num-tasks 1000 --start-task-id 1001 --end-task-id 1078  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done; 1441)  python generate_tasks.py --model NA --stage 2 --proc-id 2  --num-tasks 1000 --start-task-id 1079 --end-task-id 1472  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done)    python generate_tasks.py --model NA --stage 2 --proc-id 4  --num-tasks 604  --start-task-id 1473 --end-task-id 2077  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done)    python generate_tasks.py --model NA --stage 2 --proc-id 3  --num-tasks 3000 --start-task-id 2078 --end-task-id 2658  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (failed; 3721)  python generate_tasks.py --model NA --stage 2 --proc-id 5  --num-tasks 3000 --start-task-id 2659 --end-task-id 5658  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done) python generate_tasks.py --model NA --stage 2 --proc-id 6  --num-tasks 3000 --start-task-id 5659 --end-task-id 7746  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (failed; 8914)  python generate_tasks.py --model NA --stage 2 --proc-id 7  --num-tasks 3000 --start-task-id 7747 --end-task-id 9796  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (ongoing; but last 10794)  python generate_tasks.py --model NA --stage 2 --proc-id 8  --num-tasks 3000 --start-task-id 10747 --end-task-id 12713  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done) python generate_tasks.py --model NA --stage 2 --proc-id 9  --num-tasks 3000 --start-task-id 12714 --end-task-id 12910  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# (done) python generate_tasks.py --model NA --stage 2 --proc-id 10  --num-tasks 950 --start-task-id 9797 --end-task-id 10693  --num-dim 6 --num-data 500 --max-length 100000 --run-gpt claude --prompt-version 5 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim6_tasks13693_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels

#--------------------3
# python generate_tasks.py --model NA --proc-id 0 --num-tasks 1000 --num-dim 3 --num-data 100 --max-length 5000 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23426_pversion5 --path-tasklabels /u/ajagadish/vanilla-llama/categorisation/data/tasklabels
# python generate_tasks.py --model NA --proc-id 0 --num-tasks 100 --start-task-id 0   --num-dim 3 --num-data 100 --max-length 3000 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23459_pversion5
# python generate_tasks.py --model NA --proc-id 2 --num-tasks 100 --start-task-id 100 --num-dim 3 --num-data 100 --max-length 300 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23459_pversion5
# python generate_tasks.py --model NA --proc-id 3 --num-tasks 300 --start-task-id 200 --num-dim 3 --num-data 100 --max-length 3000 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23459_pversion5
# python generate_tasks.py --model NA --proc-id 4 --num-tasks 500 --start-task-id 500 --num-dim 3 --num-data 100 --max-length 3000 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23459_pversion5
# python generate_tasks.py --model NA --proc-id 5 --num-tasks 00 --start-task-id 800 --num-dim 3 --num-data 100 --max-length 3000 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23459_pversion5
# python generate_tasks.py --model NA --proc-id 999 --num-tasks 1 --num-dim 3 --num-data 10 --max-length 200 --run-gpt claude --prompt-version 3 --use-generated-tasklabels --file-name-tasklabels claude_generated_tasklabels_paramsNA_dim3_tasks23459_pversion5#hEHwZ6G@LwmeCR
