#!/bin/bash -l
#SBATCH -o ./logs/%A_%a.out
#SBATCH -e ./logs/%A_%a.err
#SBATCH --job-name=train_metalearner
#SBATCH --time=24:00:00
#SBATCH --constraint="gpu"
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=20G
#SBATCH --cpus-per-task=9
#SBATCH --mail-type=ALL
#SBATCH --mail-user=akshaykjagadish@gmail.com

cd ~/ermi/
module purge
module load anaconda/3/2023.03
module load gcc/13 impi/2021.9
module load cuda/12.1
module load pytorch/gpu-cuda-12.1/2.2.0
pip3 install --user ipdb torch transformers tensorboard ipdb tqdm schedulefree ivon-opt wandb

# BERMI: 2 dimensions

### l2 regulariation

## with fixed constraints
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --optimizer schedulefree --constraint --ess ${SLURM_ARRAY_TASK_ID} --offset 0 --scale 1 --job-array --ess-init 0.0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000 --optimizer schedulefree --constraint --ess 2 --ess-init 0.0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 10000 --optimizer schedulefree --constraint --ess 2 --offset 0 --scale 1 --job-array --ess-init 0.0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle

# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 100000 --ess 0.1 --offset 0.1 --job-array --scale 0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 100000 --ess 0.001 --offset 0.001 --job-array --scale 0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 100000 --ess 0.001 --offset 0.001 --job-array --scale 0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# second run id for same model
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 100000 --ess 0.1 --offset 0.1 --job-array --scale 0 --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# annealing
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 10000 --ess 7 --offset 0 --scale 1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# play
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 10000 --ess 2 --optimizer schedulefree --offset 5 --scale 0.5 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 10000 --ess 4.5 --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --restart-training --env-type claude_dim2 --num-episodes 1000000 --ess 1 --optimizer schedulefree --offset 9 --scale 0.1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle

### jobs
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000 --ess 0.001 --offset 0.001 --job-array --scale  ${SLURM_ARRAY_TASK_ID} --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 100000 --ess 0.1 --offset 0.1 --job-array --scale ${SLURM_ARRAY_TASK_ID} --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess 0.1 --offset 0.1 --job-array --scale ${SLURM_ARRAY_TASK_ID} --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess 0.1 --offset 0.1 --job-array --scale ${SLURM_ARRAY_TASK_ID} --loss nll --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --offset 0 --scale 0.1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --offset 3.5 --scale 0.1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --offset 4.5 --scale 0.1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 5 --scale 0.5 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.5 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# (9.1-9.5; rerun below as it did not finish running) python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 9 --scale 0.1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle
python mi/l2.py --paired --restart-training --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 9 --scale 0.1 --job-array --ess-init 0.001 --annealing-fraction 0.167  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle
# python mi/l2.py --paired --env-type claude_dim2 --num-episodes 1000000 --ess ${SLURM_ARRAY_TASK_ID} --optimizer schedulefree --offset 0 --scale 0.5 --job-array --ess-init 0.001 --annealing-fraction 0.25  --loss nll --max-steps 20 --num-dims 2  --first-run-id 1 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 8 --num_layers 2 --d_model 64 --num_head 8 --batch_size 512 --shuffle

### IVON

## num hidden units for optimal lambada
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 64 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 128 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 3 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 64 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 1. --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle

## train optimal smallest model for different lambdas
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --offset 10000 --scale 10000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --offset 20000 --scale 1000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --offset 0 --scale 1000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --offset 10 --scale 100 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 1000000 --train-samples 1 --offset 0 --scale 100 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# (final) python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 1000000 --train-samples 1 --offset 0 --scale 100 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.1 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8

# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --offset 20000 --scale 1000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --offset 10000 --scale 1000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --offset 30000 --scale 1000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --offset 30000 --scale 10000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1  --offset 10 --scale 100 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1  --offset 10 --scale 100 --job-array --ess ${SLURM_ARRAY_TASK_ID} --lr 0.0001 --prior-std 1.0 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8

# python mi/elbo.py --paired --env-type claude_dim2 --num-episodes 10000 --test --train-samples 1 --ess 10 --lr 0.0001 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8

## effect of number of episodes
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 50000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 10000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --batch_size 64 --shuffle

## layers for optimal lambada
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 2 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --ess 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 256 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle

## annealed models for different lambada
# python mi/train_decisionmaking.py --paired --ess 10000 --ess-init 1000000 --annealing-fraction 0.5 --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --ess 40000 --ess-init 1000000 --annealing-fraction 0.5 --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --ess 50000 --ess-init 1000000 --annealing-fraction 0.5 --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --ess 60000 --ess-init 1000000 --annealing-fraction 0.5 --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --ess 70000 --ess-init 1000000 --annealing-fraction 0.5 --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --ess 80000 --ess-init 1000000 --annealing-fraction 0.5 --env-type claude_dim2 --num-episodes 100000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --offset 10000 --scale 10000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --ess-init 1000000 --annealing-fraction 0.167 --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle
# python mi/train_decisionmaking.py --paired --offset 10000 --scale 10000 --job-array --ess ${SLURM_ARRAY_TASK_ID} --ess-init 100000 --annealing-fraction 0.167 --env-type claude_dim2 --num-episodes 300000 --train-samples 1 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --save-every 100 --print-every 10  --noise 0.0 --model-name transformer --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --batch_size 64 --shuffle

## load optimal optimal model and train with different lambadas
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000 --train-samples 1 --num-episodes  1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10000 --train-samples 1 --num-episodes 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 30000 --train-samples 1 --num-episodes 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 40000 --train-samples 1 --num-episodes 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100000 --train-samples 1 --num-episodes 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000000 --train-samples 1 --num-episodes 1000000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8
# same as above but with smaller model
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 50000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 60000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 70000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 80000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 90000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 32 --num_layers 4 --d_model 64 --num_head 8 --regularize all

## regularize only mlp weights
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10000 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 50000 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100000 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10 --train-samples 1 --num-episodes  300000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100 --train-samples 1 --num-episodes  300000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000 --train-samples 1 --num-episodes  300000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize mlp_only

## regularize only attention weights
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000  --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10000 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 50000 --train-samples 1 --num-episodes  100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100000 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100 --train-samples 1 --num-episodes 100000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 100 --train-samples 1 --num-episodes 300000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 10 --train-samples 1 --num-episodes 300000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
# python mi/train_decisionmaking.py --paired --env-type claude_dim2 --ess 1000 --train-samples 1 --num-episodes 300000 --lr 0.1 --prior-std 0.1 --loss variational --max-steps 20 --num-dims 2  --first-run-id 0 --env-name claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown --env-dir /u/ajagadish/ermi/decisionmaking/data --save-dir /u/ajagadish/ermi/decisionmaking/trained_models/ --path-to-init-weights env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0 --save-every 100 --print-every 10 --noise 0.0 --batch_size 64 --shuffle --num_hidden 256 --num_layers 6 --d_model 64 --num_head 8 --regularize attn_only
