#!/bin/bash -l
#SBATCH -o ./logs/%A.out
#SBATCH -e ./logs/%A.err
#SBATCH --job-name=simulate_metalearner
#SBATCH --time=24:00:00
#SBATCH --constraint="gpu"
#SBATCH --gres=gpu:a100:1
#SBATCH --mem=40G
#SBATCH --cpus-per-task=18
#SBATCH --mail-type=ALL
#SBATCH --mail-user=akshaykjagadish@gmail.com

cd ~/ermi/
module purge
module load anaconda/3/2023.03
module load gcc/13 impi/2021.9
module load cuda/12.1
module load pytorch/gpu-cuda-12.1/2.2.0
pip3 install --user ipdb torch transformers tensorboard ipdb tqdm schedulefree


## experiment 1
## paired
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --paired --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0_ranking
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --paired --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0_unknown
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --paired --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks8770_run0_procid1_pversionranked_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --paired --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks7284_run0_procid1_pversionunknown_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0
## unpaired
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0_ranking
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0_unknown
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks8770_run0_procid1_pversionranked_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 1 --policy greedy --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks7284_run0_procid1_pversionunknown_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0


## experiment 2
## paired
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --paired --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0_direction
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --paired --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0_unknown
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --paired --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks8220_run0_procid1_pversiondirection_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --paired --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks7284_run0_procid1_pversionunknown_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0
## unpaired
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0_direction
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --model-name env=synthetic_dim4_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0_unknown
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks8220_run0_procid1_pversiondirection_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 2 --policy greedy --model-name env=claude_generated_functionlearningtasks_paramsNA_dim4_data20_tasks7284_run0_procid1_pversionunknown_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0


## experiment 3
## paired
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --model-name env=synthetic_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0_unknown
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --model-name env=claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_run=0
## unpaired
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --model-name env=synthetic_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0_unknown
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --model-name env=claude_generated_functionlearningtasks_paramsNA_dim2_data20_tasks9254_run0_procid0_pversion2_unknown_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedFalse_lossnll_run=0

## BERMI
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess ${SLURM_ARRAY_TASK_ID} --job-array --offset 30000 --scale 100 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess ${SLURM_ARRAY_TASK_ID} --job-array --offset 30000 --scale 100 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess None --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess 1000000.0 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000.0_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess 1.0 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.0003_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1.0_std0.1_run=0

## hyper parameter search
## L2 Regularisation
### annealed models
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.1_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.2_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.3_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.4_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.6_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.7_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.8_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.9_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.0_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.1_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.2_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.3_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.6_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.7_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.8_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.8_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.8_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess1.9_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.0_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.1_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.2_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.3_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.4_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.6_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.7_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.8_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess2.9_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.0_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.0_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess5.0_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess5.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess6.0_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess6.5_std0.1_run=1_essinit0.001_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess7.0_std0.1_run=1_essinit0.001_annealed

python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.6_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.7_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.8_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.9_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.0_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.1_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.2_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.3_std0.1_run=1_essinit0.001_annealed
python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.4_std0.1_run=1_essinit0.001_annealed

python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=8_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.6_std0.1_run=1_essinit0.001_annealed

# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.003_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.01_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess0.1_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess3.0_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess4.0_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0003_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossnll_ess5.0_std0.1_run=0

# hidden units
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=64_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=128_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=64_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=3_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0

# #prior stds
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std1.0_run=0

# # cosine scheduler
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0_cosineschedular

# annealing lambdas
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess20000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess30000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess40000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess60000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess70000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess80000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess90000_std0.1_run=0_essinit100000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0_essinit100000.0_annealed

# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess20000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess30000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess40000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess60000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess70000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess80000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess90000_std0.1_run=0_essinit1000000.0_annealed
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0_essinit100000.0_annealed

# for different lambdas, 100k episodes, 1.0 std, learning rate 0.0001, cosine scheduler
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess110_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess210_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess310_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess410_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess510_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess610_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess710_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess810_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess910_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1110_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1210_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1310_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1410_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1510_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1610_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1710_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1810_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1910_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2110_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2210_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2310_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2410_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2510_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2610_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2710_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2810_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2910_std1.0_run=0

# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess2010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess3010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess4010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess5010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess6010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess7010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess8010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess9010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess11010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess12010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess13010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess14010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess15010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess16010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess17010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess18010_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess19010_std1.0_run=0

# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess31000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess32000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess33000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess34000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess35000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess36000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess37000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess38000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess39000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess40000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess41000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess42000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess43000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess44000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess45000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess46000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess47000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess48000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess49000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std1.0_run=0

# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess ${SLURM_ARRAY_TASK_ID} --job-array --offset 10 --scale 1000 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess ${SLURM_ARRAY_TASK_ID} --job-array --offset 31000 --scale 1000 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0


# smallest model
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess20000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess30000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess40000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess60000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess70000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess80000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess90000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0
## slower lr and higher std 1-30k
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model?aradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess30000_std1.0_run=0
## slower lr and higher std 10-15k ess
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess11000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess12000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess13000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess14000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess15000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess20000_std1.0_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=32_lr0.0001_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess21000_std1.0_run=0





# policy
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess 1000000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --ess 1000000 --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0

# num of layers
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 1000000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 1000000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=2_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0

# num of episodes
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired  --model-name env=claude_dim2_model=transformer_num_episodes10000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired  --model-name env=claude_dim2_model=transformer_num_episodes50000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired  --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired  --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0

# strength of regularization: all weights
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 1000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0_regall 
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 10000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 30000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 50000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy bernoulli --paired --ess 60000 --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_essNone_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess30000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess40000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes1000000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess60000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess70000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess80000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess90000_std0.1_run=0_regall
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=32_lr0.1_num_layers=4_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0_regall

# strength of regularization: mlp weights 
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100_std0.1_run=0_regmlp_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000_std0.1_run=0_regmlp_only

# strength of regularization: attn weights
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10000_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess50000_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100000_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes100000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess10_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess100_std0.1_run=0_regattn_only
# python mi/simulate_model.py --paradigm decisionmaking --task-name binz2022 --exp-id 3 --policy greedy --paired --use-filename --model-name env=claude_dim2_model=transformer_num_episodes300000_num_hidden=256_lr0.1_num_layers=6_d_model=64_num_head=8_noise0.0_shuffleTrue_pairedTrue_lossvariational_ess1000_std0.1_run=0_regattn_only

